---
- debug: msg="Install Mode is {{mesos_install_mode}}"

- name: install deps (RHEL)
  yum: >
    name={{item}}
    state=installed
  with_items:
    - python-pip
    - python-devel
  when: ansible_os_family == "RedHat"

- find: paths=/usr/lib/python2.7/site-packages/mesos.cli-0.25.0.dist-info file_type=directory patterns="*"
  register: empty_mesos_cli_dist

- name: remove bad pip directory
  file: /usr/lib/python2.7/site-packages/mesos.cli-0.25.0.dist-info state=absent
  when: empty_mesos_cli_dist.matched|int != 0

- name: install python module consulate
  pip: >
    name={{item}}
  with_items:
    - mesos.cli
    - mesos.interface
