---
- name: install Mesos DNS
  get_url: url={{mesos_dns_url}} dest=/usr/local/bin/mesos-dns
  tags: bootstrap

- name: create conf directory
  file: path=/etc/mesos/dns state=directory
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: copy mesos-dns-service.conf
  template: src=mesos-dns.service.j2 dest=/etc/systemd/system/mesos-dns.service mode=744
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  notify:
    - Reload daemon
    - Restart mesos-dns

- name: copy mesos-dns.conf
  template: src=conf-mesos-dns.j2 dest=/etc/mesos/dns/config.json
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-dns
