---
# == Work Dir for replicated log
- name: create work dir
  file: path={{ mesos_work_dir }} state=directory

# == Remove default configs
- name: Remove Default Mesos Configs
  file: state=absent path=/etc/mesos/

- name: Remove Mesos ZK File from RPM
  file: state=absent path=/etc/mesos/zk

- name: Remove Default Mesos-Master Config from RPM
  file: state=absent path=/etc/mesos-master/

- name: Remove Default Mesos-Slave Config from RPM
  file: state=absent path=/etc/mesos-slave/

# == Configure and recreate
- debug: "{{zookeeper_hostnames | to_json}}"
- name: Mesos default config file
  template: src=conf-mesos.j2 dest=/etc/default/mesos
  notify:
    - restart mesos-master
    - restart mesos-slave

- name: create Mesos Master config dir
  file: path=/etc/mesos/master state=directory
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: create Mesos Slave config dir
  file: path=/etc/mesos/slave state=directory
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- name: create Mesos HTTP credentials dir
  file: path=/etc/mesos/http state=directory
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- name: Copy framework password file
  template: src=frameworkpassword.j2 dest=/etc/mesos/frameworkpasswd mode=400

- name: Mesos Master credentials file
  template: src=mesos-master-credentials.j2 dest=/etc/mesos/master/credentials mode=600 owner=root group=root
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  notify:
    - restart mesos-master

- name: Mesos Master config file
  template: src=conf-mesos-master.j2 dest=/etc/default/mesos-master mode=600
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  notify:
    - restart mesos-master

- name: Mesos master rsyslog conf
  template: src=rsyslog-master.j2 dest=/etc/rsyslog.d/mesos-master.conf
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  notify:
    - restart mesos-mesos
    - restart rsyslog

- name: Mesos Slave credential file
  template: src=mesos-slave-credential.j2 dest=/etc/mesos/slave/credential mode=600 owner=root group=root
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
  notify:
    - restart mesos-slave

- name: Mesos Slave config file
  template: src=conf-mesos-slave.j2 dest=/etc/default/mesos-slave
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
  notify:
    - restart mesos-slave

- name: Check if upstart exists
  stat: path=/etc/init/
  register: etc_init

- name: Mesos master upstart script
  template: src=init-mesos-master.j2 dest=/etc/init/mesos-master.conf
  when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and etc_init.stat.exists == true
  notify:
    - restart mesos-master

- name: Mesos slave upstart script
  template: src=init-mesos-slave.j2 dest=/etc/init/mesos-slave.conf
  when: (mesos_install_mode == "slave" or mesos_install_mode == "master-slave") and etc_init.stat.exists == true
  notify:
    - restart mesos-slave

- name: Mesos slave rsyslog conf
  template: src=rsyslog-slave.j2 dest=/etc/rsyslog.d/mesos-slave.conf
  when: (mesos_install_mode == "slave" or mesos_install_mode == "master-slave")
  notify:
    - restart mesos-slave
    - restart rsyslog

- name: Check if systemd exists
  stat: path=/usr/lib/systemd/system/
  register: systemd_check
  
- name: Mesos master systemd script
  template: src=mesos-master.service.j2 dest=/usr/lib/systemd/system/mesos-master.service
  when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and systemd_check.stat.exists == true
  notify:
    - reload daemon
    - restart mesos-master

- name: Mesos slave systemd script
  template: src=mesos-slave.service.j2 dest=/usr/lib/systemd/system/mesos-slave.service
  when: (mesos_install_mode == "slave" or mesos_install_mode == "master-slave") and systemd_check.stat.exists == true
  notify:
    - reload daemon
    - restart mesos-slave

- name: Disable mesos-master service
  service: name=mesos-master enabled=no
  when: mesos_install_mode == "slave" and systemd_check.stat.exists == true

- name: Disable mesos-slave service
  service: name=mesos-slave enabled=no
  when: mesos_install_mode == "master" and systemd_check.stat.exists == true
