---

# While waiting for https://github.com/ansible/ansible-modules-core/issues/191
- name: reload daemon
  command: systemctl daemon-reload
  
# i.e. upgrade mesos, templates stay the same...
- name: restart mesos-master
  service: name=mesos-master state=restarted
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: restart mesos-slave
  service: name=mesos-slave state=restarted
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- name: restart rsyslog
  service: name=rsyslog state=restarted
